apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-api-permissions
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]  # subresource로 별도 정의
  verbs: ["create", "get"]  # 둘 다 필요
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-api-group-binding
subjects:
- kind: Group
  name: auth-api-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: auth-api-permissions
  apiGroup: rbac.authorization.k8s.io